//taxpayerReturn
export const UPDATE_TAXPAYER_RETURN_FIELD = 'UPDATE_TAXPAYER_RETURN_FIELD';
export const RESIDENCE_HISTORY_STATE_SELECT = 'RESIDENCE_HISTORY_STATE_SELECT';
export const RESIDENCE_HISTORY_STATE_MONTH_SELECT = 'RESIDENCE_HISTORY_STATE_MONTH_SELECT';
export const RESET_RESIDENCE_HISTORY = 'RESET_RESIDENCE_HISTORY';
export const UPDATE_DEPENDENT_FIELD = 'UPDATE_DEPENDENT_FIELD';
export const ADD_DEPENDENT = 'ADD_DEPENDENT';
export const REMOVE_DEPENDENT = 'REMOVE_DEPENDENT';

//ui
export const CONFIRM_SINGLE_STATE = 'CONFIRM_SINGLE_STATE';
export const UPDATE_STEP = 'UPDATE_STEP';
export const ADD_INVALID_FIELD = 'ADD_INVALID_FIELD';
export const ADD_INVALID_FIELDS = 'ADD_INVALID_FIELDS';
export const REMOVE_INVALID_FIELD = 'REMOVE_INVALID_FIELD';
export const REMOVE_INVALID_FIELDS = 'REMOVE_INVALID_FIELDS';
export const UPDATE_RESULT = 'UPDATE_RESULT';
