export const UPDATE_TAXPAYER_RETURN_FIELD = 'UPDATE_TAXPAYER_RETURN_FIELD';
export const RESIDENCE_HISTORY_STATE_SELECT = 'RESIDENCE_HISTORY_STATE_SELECT';
export const RESIDENCE_HISTORY_STATE_MONTH_SELECT = 'RESIDENCE_HISTORY_STATE_MONTH_SELECT';
export const RESET_RESIDENCE_HISTORY = 'RESET_RESIDENCE_HISTORY'

export const CONFIRM_SINGLE_STATE = 'CONFIRM_SINGLE_STATE';
