export default {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  DC: "District of Columbia"
};

export const statesThatDidNotExpandMedicaid = {
  "2017" : ["AL", "FL", "GA", "ID", "KS", "ME", "MO","MS", "NC", "NE", "OK", "SC", "SD", "TN","TX", "UT", "VA", "WY", "WI"],
  "2016" : ["AL", "FL", "GA", "ID", "KS", "LA", "ME","MO", "MS", "NC", "NE", "OK", "SC", "SD","TN", "TX", "UT", "VA", "WY", "WI"],
  "2015" : ["AL", "AK", "FL", "GA", "ID", "IN", "KS","LA", "ME", "MO", "MS", "MT", "NC", "NE","OK", "SC", "SD", "TN", "TX", "UT", "VA","WY", "WI"],
  "2014" : ["AL", "AK", "FL", "GA", "ID", "IN", "KS","LA", "ME", "MO", "MS", "MT", "NC", "NE","NH", "OK", "PA", "SC", "SD", "TN", "TX","UT", "VA", "WY", "WI"]
};
